# Generated by Django 4.2.3 on 2023-07-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso em KG', max_digits=5, verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade em ML', max_digits=6, verbose_name='Quantidade')),
                ('date', models.DateField(auto_now_add=True, help_text='Data do consumo', verbose_name='Data')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intake', to='tracker.user', verbose_name='Usuário')),
            ],
        ),
    ]
